packages:
  - 'apps/*'
  - 'libs/*'

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  core-js-pure: true
  cpu-features: true
  esbuild: true
  less: true
  nx: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
